trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - python
    - pipelines/python.yml
    
strategy:
  matrix:
    Python38:
      python.version: '3.8'
    Python39:
      python.version: '3.9'
    Python310:
      python.version: '3.10'

resources:
  repositories:
  - repository: m365Pipelines
    type: git
    name: 1ESPipelineTemplates/M365GPT
    ref: refs/tags/release

extends:
  template: v1/M365.Official.PipelineTemplate.yml@m365Pipelines
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: windows-2022
      os: windows

    customBuildTags:
    - ES365AIMigrationTooling

    stages:
    - stage: stage
      jobs:
      - job: job
        templateContext:
          outputs:
          - output: pipelineArtifact
            displayName: 'Publish Artifact'
            targetPath: '$(Build.ArtifactStagingDirectory)/python/packages/ai'
            artifactName: Packages

        steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '$(python.version)'
          displayName: 'Use Python $(python.version)'

        - script: |
            python -m pip install --upgrade pip
            pip install poetry
            python scripts/install.py
          displayName: 'Install Dependencies'
          workingDirectory: 'python'

        - script: |
            python scripts/check.py
          displayName: 'Check'
          workingDirectory: 'python'

        - script: |
            python scripts/build.py
          displayName: 'Build'
          workingDirectory: 'python'

        - script: |
            python scripts/test.py
          displayName: 'Test'
          workingDirectory: 'python'

        - script: |
            python scripts/lint.py
          displayName: 'Lint'
          workingDirectory: 'python'

        - task: CopyFiles@2
          inputs:
            sourceFolder: '$(Build.SourcesDirectory)'
            contents: |
              python/packages/ai/dist/*
            targetFolder: $(Build.ArtifactStagingDirectory)